### ISSUE TITLE
domain name support layout switching

### ISSUE THREAD

**Issue by wenzis** [sitemesh/sitemesh3#73] opened 2014-12-30 03:39 UTC
org.sitemesh.webapp.WebAppContext.getRequestPath(), the method given the project path,
such as,there is two url : http://l192.168.1.100:8080/login and http://l192.168.1.111:8080//login
to use a different layout, should I do?

**Comment by codeconsole** [comment] 2015-05-15 03:11
Duplicate of #71

**Closed by codeconsole** 2015-05-15 03:11 UTC
